UI redesign
Amijakan/mochatto pull request #180
Opened 2021-09-27 18:27 UTC by siberowl

## Which Issue was this PR made for?

- Closes #171

## What is within the scope with this PR

Redesigning the ui.

## What is NOT in the scope with this PR

### Related Issue

## Other sidenotes that reviewer should be aware of

2021-09-27 18:28 UTC, siberowl commented
![image](https://user-images.githubusercontent.com/34047281/134965017-25936f33-5438-4afa-8479-4cc4aae82708.png)
![image](https://user-images.githubusercontent.com/34047281/134965059-1c7cc22c-65ab-4d39-aff9-ba4c50dbb900.png)

2021-09-28 14:24 UTC, Njima1572 approved these changes
UI Seems way nicer.

There is a weird bug with toggling active, can be solved later with different issue once we know what's the problem.

2021-09-28 14:24 UTC, Njima1572 commented on client/src/pages/RoomPage.tsx
> +        history.go(0);
Love the shortcut keys

2021-09-28 14:44 UTC, Njima1572 requested changes

2021-09-28 14:44 UTC, Njima1572 commented on client/src/pages/RoomPage.tsx
>        } else if (e.code === "Space") {
Space actually also triggers onClick when the button is focused, so might not be the good choice.
Change this to 's' for status and ',' for preferences?

2021-09-28 14:54 UTC, Njima1572 approved these changes
LGTM

2021-09-28 14:55 UTC, merged